// base
export const FETCH_CARS = 'FETCH_CARS';
export const FETCH_CARS_START = 'FETCH_CARS_START';
export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';
export const FETCH_CARS_ERROR = 'FETCH_CARS_ERROR';
export const APPLY_FILTER = 'APPLY_FILTER';
export const RESET_FILTER = 'RESET_FILTER';
export const SET_FILTER_OPTIONS = 'SET_FILTER_OPTIONS';

// filterOptions
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const CLEAR_FILTER_SELECTED_OPTIONS = 'CLEAR_FILTER_SELECTED_OPTIONS';

// rent
export const SELECT_CAR = 'SELECT_CAR';
export const AGREE_WITH_CONDITIONS = 'AGREE_WITH_CONDITIONS';
export const RENT_CAR_SUCCESS = 'RENT_CAR_SUCCESS';
export const RENT_CAR_ERROR = 'RENT_CAR_ERROR';
export const SET_END_DATE = 'SET_END_DATE';
export const SET_START_DATE = 'SET_START_DATE';
export const SET_CUSTOMER_FIRST_NAME = 'SET_CUSTOMER_FIRST_NAME';
export const SET_CUSTOMER_LAST_NAME = 'SET_CUSTOMER_LAST_NAME';
export const SET_VALIDATE_STATUS = 'SET_VALIDATE_STATUS';
